name: Test Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on:
      - self-hosted
      - Windows
      - X64
    steps:
    - name: Verify Runner
      run: echo "Runner is active and picking up jobs!"
